<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Debug controller for the Debug module
 *
 * @author		 OSS Dev Team
 * @package	 Modules\Debug\Controllers
 */
class Debug extends MX_Controller {
	
	/**
	 * Constructor method
	 */
	function __construct() 
	{
		parent::__construct();
		$this->load->model('debug/debug_model');
		//$this->load->model('auth/ion_auth_model');
		$this->output->enable_profiler(TRUE);
		$this->benchmark->mark('my_controller_start');
		$this->benchmark->mark('my_controller_end');
	}
	public function get_data_info ()
	{
		$bechmark_users = $this->debug_model->get_benchmark_users();
		
		foreach ($bechmark_users as $key => $bechmark_user)
		{
			if (in_array($_SESSION['user_id'], $bechmark_user))
			{
				$submit_button = $this->input->post('submit');
        		if (!empty($submit_button)) 
				{
					$this->data['result'] = $this->debug_model->get_result($_POST['data_info']);
					echo "<pre>";
					print_r($this->data['result'] );
					echo "</pre>";
				}
				$data['main_content'] = 'debug/show';
       			$data['title'] = 'Get Data Info';
        		$this->load->view('layouts/default', $data);
			}
		}
	}
	public function debug_test()
	{
		//phpinfo();
		$fields1 = $this->db->get('users')->result_array();
		echo "<pre>";
		print_r($fields1);
		echo "</pre>";
		//$fields1 = $this->db->get('tickets_files')->result_array();
		
		//$query1 = $this->db->get('customers_info')->result_array();
		/*
		die;
		echo "<pre>";
		print_r($fields1);
		echo "</pre>";
		*/
		/*
		$this->db->query('alter table "tickets" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
		$this->db->query('alter table "tickets_logs_texts" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
		$this->db->query('alter table "tickets_logs" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
		$this->db->query('alter table "customers_info" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
		$this->db->query('alter table "tickets_files" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
	
		$this->db->truncate('tickets');
		$this->db->truncate('tickets_logs_texts');
		$this->db->truncate('tickets_logs');
		$this->db->truncate('customers_info');
		$this->db->truncate('tickets_files');
		*/			
	}
	
}
	