<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Debug controller for the Debug module
 *
 * @author		 OSS Dev Team
 * @package	 Modules\Debug\Controllers
 */
class Debug extends MX_Controller {
	
	/**
	 * Constructor method
	 */
	function __construct() 
	{
		parent::__construct();
		$this->load->model('debug/debug_model');
		//$this->load->model('auth/ion_auth_model');
		$this->output->enable_profiler(TRUE);
		$this->benchmark->mark('my_controller_start');
		$this->benchmark->mark('my_controller_end');
	}
	
	public function debug_test()
	{
		phpinfo();
		//$fields1 = $this->db->get('tickets_files')->result_array();
		//$query1 = $this->db->get('customers_info')->result_array();
		/*echo "<pre>";
		print_r($fields1);
		echo "</pre>";
		die;*/
		/*
		$this->db->query('alter table "tickets" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
		$this->db->query('alter table "tickets_logs_texts" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
		$this->db->query('alter table "tickets_logs" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
		$this->db->query('alter table "customers_info" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
		$this->db->query('alter table "tickets_files" modify ("id" number(11) GENERATED BY DEFAULT AS IDENTITY start with 1)');
	
		$this->db->truncate('tickets');
		$this->db->truncate('tickets_logs_texts');
		$this->db->truncate('tickets_logs');
		$this->db->truncate('customers_info');
		$this->db->truncate('tickets_files');
		*/			
	}
	
}
	